language: python
python:
- 3.6
- 3.7
- 3.8
before_install:
- sudo apt update
- sudo apt install libdb-dev libdb++-dev
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov
install:
- pip install .
script:
- pytest
after_success:
- codecov
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: n3+mQpufdUttwn0D4CvhomXlpiz/iU4+b0XezLhku08Zlrj6fPnpMOqk88GpYRsGB7Zm5XI0iS5J5aJn1iRcj02JrlMkG9l+Rd7L2J1s7X3/DZcOP9H+IatxM7hVf8m+m4/gk+QB+JWK8WYnJnbIF6IQ99HziqvsrNo+TjKZshZx5bUfxVS997SHEh01XdC0zMaeHxQH8mx8DBRvs4eRJKntRhFuF1gGkMZa6gk7UC9Y7O+6QP2lVetVhFM9v0I7Asmh4AvUjmtzLeXs+24SgxmNtOmn3whKwRLcdbQkq7rdFKjoYLwyWuND62epICZVOo5YA22l2H9zs5PABmJulvYqNNymGZDFHQEZTlBBog5ciHH7V1nYJKBrvA0OCRGVt3mg5VTbfjORpXg7lW+cZ4bfaRisKe7M5HMKRd/j1xMNfc1fD1TftKoxge8GVxH60dfWRUJ1rbnQw0589FMCB5JRm/CI8r9TJ8h3lRA+AWKnohmdYahaU1pwKnZuXyssFjNqlgV8sjhgq22nxiB0F1OFO4PpApneP6tlLvEaU6EUQooXYxdxRC8Vz8RVr/i11AbQcy0Q8m61VVB+BwnR1Gye5MJ1QiIUWdU7wwWa5WODlR8cg7Wm9wp19DnHW0Y7dK9xDjp+qPDzE4Y0kEz4W3d4hPAt3LltlE4TFmqj8jI=
  skip_cleanup: true
  on:
    branch: master
  skip_existing: true
