language: python
python:
- 3.6
- 3.7
- 3.8
before_install:
- sudo apt update
- sudo apt install libdb-dev libdb++-dev
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov
install:
- pip install .
script:
- pytest
after_success:
- codecov
deploy:
  provider: pypi
  username: __token__
  password:
    secure: QQIy5GXQe4jHBg0wVyGYkFJTD728lrSNvbMFvGVWAK1JsPSZTEU7xfuSHwD0iFTtMe3YSZ/hHLhzLa+Mbj/cvXBAiieGwc8q0iVqwy43gQFYgdYu1AoAivuBZGWTmBhUYE2M0IpxIfaq1TXR2xxNQEL5RteVfIZv/Sp2QxT5euOwRTW70bVcuUw0qRnrXAPzXGDiGGZsPpiM/QZKSt6pt0orAup85OP9Jdz5jCcHPzWvnrEqo+pn5H8w+oEAv1HAxF3vHmEtbi88teVJV08p02R1It4lZ/UFHuQofjBXBZRqYAlQ47aa874slM97f6E6gFWlq0COUrckmJvDgjNaztD88C/sQE7NY9w0Grmfw7sIxe9QZyv1A3y0ULvhUNP042ehDGbWuPv3/0qOpnTDG4k+i8jJQAWQOJeSoRUhTDjuW39GXVtUa0JX1aUtDx0rPzFUKo6eee5WoEpQiEKhqdvqLhn5FIddPj4RGlbid1BXRm501ibr8GDdtFAmjvi+tgrK1BdJFS/HkdSTdPhXL+4SFY3EyIuEl24JO8ATYCMcPBSOpVm1iinw5TW5tR06bn6xngk4T+BTKUsT4Jjf1dJXGKJK9/cX/fI3TaLXcVS9mMnBwcdFIVU1IZDHcCi5LprjOFugkIma+YkdhyC3xTHGBtTgLKE88RXUqb2BCKA=
  skip_cleanup: true
  on:
    branch: master
  skip_existing: true
