language: python
python:
- 3.6
- 3.7
- 3.8
before_install:
- sudo apt-get update
- sudo apt-get install libdb-dev libdb++-dev
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov
install:
- pip install .
script:
- pytest
after_success:
- codecov
deploy:
  provider: pypi
  username: __token__
  password:
    secure: dQYXWF1fTtHJ41hpL+BcCQsaYL08a6uQwcIae6dPLR8xpAqzQt8KM/SQ9B3FGrXXz9XnctUfoWK5m1zHKq2COFpEi9M9Hxu45SzBR0nlS22r97k8cvLz7viyFPvlqNlRk8cFJX8ssc9lZ4U+rRyoGblOKLEiAVCzo0RwGmWTHsogd17pLokFA1GTjxqlYyTzz5F/Z079ufjhIHb6BW8OyY4Akv5L39Jw0JCT8wFR0QS1xmC/6haOnL+A2vJ8KgVXQaYzoeo1FmMVu0OOemxjtuUpILPbGAXN7FIsuhaxIzMWka8CvtPjtWgUmVa2BjsvUzg2YSaOdbMqC3i7LKRK+FbSH3Q2ZbJsuqI7SMJ+47puOHC3fV7Fb8D140vc+TUHiN7mlmQhgQ0T7hOFv3R2sOCDygV018DKPs4qiQaesQ3r7LuDREg7MELdTVuOL68xlBAcquo+raacdsX9QshdMKHgLw2MK7kAxJaDhW3KQz9ZOzYeXdcLjWlP78say372EqbpB4S3GLuRiVMv1ebJ+1Cq72kwGnC1pzQgQZE01PfMnF0HXKBNLouljZmc7MwZsZSllJpaA3t67qibSW4eAqQfMrmlTi5/P7Z8vBEUzgAtYxr74yAUDPQstkWYtbwHCZVIeBuy8GgH43CKV/oE+ZNKA5P+ro2prgfnysqbFis=
  skip_cleanup: true
  on:
    branch: master
  skip_existing: true
