name: run-tests
on: [push, pull_request]
jobs:
  unitTests:
    name: Unit Tests Runner
    runs-on: ubuntu-latest
    environment:
      name: CodeCov
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python3 -m pip install -U pip
      - run: sudo apt-get update
      - run: sudo apt-get -y install libdb-dev libdb++-dev
      - run: python3 -m pip install numpy==1.20.3
      - run: python3 -m pip install -r requirements.txt
      - run: pip install .
      - run: python3 -m pytest --cov=simpleBDB --cov-report=xml tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          path_to_write_report: ./codecov_report.txt
          verbose: true
  deploy:
    runs-on: ubuntu-latest
    needs: unitTests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}